import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, DateTime, Boolean, ForeignKey, Integer, Float
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import declarative_base, relationship
from pgvector.sqlalchemy import Vector

Base = declarative_base()

class User(Base):
    __tablename__ = 'users'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(Text, unique=True, nullable=False)
    password = Column(Text, nullable=False)
    role = Column(Text, default='user')
    created_at = Column(DateTime, default=datetime.utcnow)

class TaskRun(Base):
    __tablename__ = 'task_runs'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id'))
    goal = Column(Text, nullable=False)
    status = Column(Text, default='pending')
    plan = Column(JSONB)
    result = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime)

    # Relationships
    user = relationship("User")
    memories = relationship("AgentMemory", back_populates="run")
    logs = relationship("ObsLog", back_populates="run")
    attributions = relationship("FailureAttribution", back_populates="run")

class AgentMemory(Base):
    __tablename__ = 'agent_memory'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id'))
    goal_text = Column(Text)
    embedding = Column(Vector(384))
    findings = Column(JSONB)
    run_id = Column(UUID(as_uuid=True), ForeignKey('task_runs.id'))
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    user = relationship("User")
    run = relationship("TaskRun", back_populates="memories")

class ObsLog(Base):
    __tablename__ = 'obs_logs'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey('task_runs.id'))
    agent = Column(Text)
    tool = Column(Text)
    input_summary = Column(Text)
    output_summary = Column(Text)
    latency_ms = Column(Integer)
    success = Column(Boolean)
    error_msg = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    run = relationship("TaskRun", back_populates="logs")

class FailureAttribution(Base):
    """
    Stores root-cause analysis for failed workflow runs.
    
    Generated by the Failure Attribution Engine (agents/attribution.py)
    which queries obs_logs, identifies the first failure point, and uses
    an LLM to produce a causal explanation.
    
    Research Reference: Addresses the gap identified in ICML 2025 
    (arXiv:2505.00212) where best existing methods achieve only 53.5% 
    attribution accuracy in multi-agent systems.
    """
    __tablename__ = 'failure_attributions'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_id = Column(UUID(as_uuid=True), ForeignKey('task_runs.id'), nullable=False)
    root_cause_agent = Column(Text)           # e.g., "planner", "research", "critic"
    root_cause_step = Column(Text)            # e.g., "llm_call", "web_search"
    confidence = Column(Float, default=0.0)   # 0.0 to 1.0
    explanation = Column(Text)                # One-sentence causal explanation
    context_logs = Column(JSONB)              # Surrounding log entries for debugging
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    run = relationship("TaskRun", back_populates="attributions")
